version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80"

  backend:
    build: ./backend
    container_name: backend
    expose:
      - "8000"
    environment:
      DATABASE_URL: "postgresql://app:changethis123@db:5432/app"

  db:
    image: postgres:14.12
    container_name: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: changethis123
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:
